spring:
  application:
    name: monzo-crawler

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,beans,env,metrics
  simple:
    metrics:
      export:
        enabled: true